config/routes.rb
Simpleweb::Application.routes.draw do
  

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
   root :to => 'main#index'

   match "/auth/:provider/callback" => "sessions#create"
   match "/signout" => "sessions#destroy", :as => :signout


   resources :sessions
   resources :contacts

   scope :controller => :contacts do
    get 'index'
   end

   scope :controller => :main do
    get 'contacts'
   end



  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid, :email, :token, :refresh_token, :token_expiry, :expires_at

  #Validations


  #Methods
  def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["info"]["name"]
    user.email = auth["info"]["email"]
    user.token = auth["credentials"]["token"]
    user.refresh_token = auth["credentials"]["refresh_token"]
    user.token_expiry = DateTime.now #+ 50.minutes
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

# USe Helper in Views and Contollers
helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  require 'will_paginate/array'
  include Support::Contacts


  def index
    @mycontacts = getcontact.to_a.paginate(:page => params[:page], :per_page => 30)
    @mycontacts.sort!{|a, b| a.xpath('xmlns:title').text <=> b.xpath('xmlns:title').text}
  end

  def new

  end

  def create

  end

  def edit

  end

  def show
  

  end

  def update

  end

  def destroy

  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController
  include Support::Contacts
  

  def index

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/contacts/index.html.erb
<h1>My Contacts</h1>
<%= link_to "Sign Out", signout_path %>

<% @mycontacts.each do |c| %>
<p> Name: <%= c.xpath('xmlns:title').text %>  Email: <%= c.xpath('gd:email/@address').text %> <%= link_to "Update Contact" %></p> 

<% end %>

<%= will_paginate @mycontacts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpleweb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1> Home Page </h1>

<% if current_user %>
  Welcome <%= current_user.email %>!<br>
  <%= link_to "Sign Out", signout_path %><br>
  <%= link_to "Get my Contacts", contacts_path %><br>
<% else %>
  <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
<% end %>